### ISSUE TITLE
service should generate errors but not crash if dir not present

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/iobox-win32#11]
If the user specifies a directory in the config, say the log dir, but the dir does not exist. It should log an error and stop but not throw an exception.

I will label this as a question because I'm not sure what behavior I saw before. I thought it was an exception rather than a clean log message.

**Comment by hongsudt** [comment]
I agree with @robes that, we should automatically generate those directories if they don't exist. The user will need to know where to drop the input files anyway, so I am not sure forcing users to manually create directories will do much help.

**Comment by karlcz** [comment]
I don't think @robes said to generate directories automatically, nor
do I think we should create directories automatically.  We should
report clear errors and exit rather than crash.

Given that these iobox rules MAY involve large files and important
data, I think we should tend to fail-safe rather than make guesses as
to what to do next when there are inconsistencies. The config file
might be wrong, and there might be other data and or disparate
filesystems involved, with lots of ugly effects if we forge ahead and
process the wrong directory.

**Comment by robes** [comment]
Along these lines, the iobox should probably validate all of the directories. You don’t want to get to the ‘reject’ or ‘failure’ stage and then have iobox terminate. We should get the config, validate it, validate external references (directories) that it references, and then proceed. I’m not sure how far we want to take that but this much seems reasonable.

**Comment by svoinea** [comment]
Currently, the service is stopped gracefully (i.e. no crash) if any of the monitored directories (inbox, success, failure, retry or transfer) does not exist. These errors are already logged in the log file specified in the configuration file.

The service is implemented as an ever loop in which all exceptions are caught and logged. Normally, it will never crash. It can be stopped through the Windows Services Manager.

If the configuration file does not exists or it has an invalid JSON syntax, then the error will be reported as described in the issue #13.

While it is not mandatory to specify a log file in the configuration file is , it is recommended. The absence of a log file translates in using a NullHandler which does not do any formatting or output (it is essentially a ‘no-op’ handler).

**Comment by robes** [comment]
@svoinea Your description sounds right to me.
