### ISSUE TITLE
Use Content-Type: text/csv for POST and PUT requests

### ISSUE THREAD

**Issue by svoinea** [informatics-isi-edu/iobox-win32#17]
`Content-Type: text/csv` reports an error if any of the specified column does not exist in the table, while `application/json` ignores the columns that are not present in the table.

**Comment by svoinea** [comment]
Fixed in commit 3e3fdddd31fa69fef923fa63679dbc3461831c2b

Ready for review.

**Comment by karlcz** [comment]
@svoinea I can only assume the goal here is to get more strict behavior and abort with errors if the ruleset produced columns that don't exist in the schema?  What about the opposite?  Are you now going to require that all columns be populated by rules, or will you build the CSV according to the schema and provide empty (null) fields when not populated by rules?

It seems to me that iobox could do all these checks itself by fetching the schema and interpreting the ruleset outputs, rather than depending on ERMrest to enforce it based on using CSV versus JSON inputs. This would also allow more flexibility to have iobox ruleset options to control how strict or lenient the behavior is in a particular deployment.

**Comment by karlcz** [comment]
Adding @robes @hongsudt @carlkesselman to discussion...

**Comment by svoinea** [comment]
Currently, the iobox does not do any validation of the ermrest requests. It takes ad-litteram the specification from the configuration file and executes the request.

I think the problem was related to the fact that ermrest behaves differently for the same request based on the Content-Type.
